name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        numpy-version: ['2.1', 'dev']
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.numpy-version }}" == "dev" ]]; then
            python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy;
          else
            python -m pip install 'numpy==${{ matrix.numpy-version }}';
          fi
          python -m pip install -r requirements-dev.txt
      - name: Run Tests
        run: |
          pytest

          # Make sure it installs
          pip install .
